---
- name: Configure Keylime Agent
  hosts: keylime_agent
  become: true
  pre_tasks:
    - name: Ensure Python 3 is available
      dnf:
        name: python3
        state: present
    - name: Install libselinux-python3
      dnf:
        name: libselinux-python3
        state: present    
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
  roles:
    - ansible-keylime
    - tpm_setup
  tasks:
    - name: Set Keylime agent environment variables for root user
      blockinfile:
        path: /root/.bashrc
        marker: "# {mark} KEYLIME AGENT ENV VARS"
        block: |
          export KEYLIME_AGENT_IP="192.168.33.10"
          export KEYLIME_AGENT_PORT="9002"
          export KEYLIME_AGENT_CONTACT_IP="192.168.33.10"
          export KEYLIME_AGENT_CONTACT_PORT="9002"
          export KEYLIME_AGENT_REGISTRAR_IP="192.168.33.11"
          export KEYLIME_AGENT_REGISTRAR_PORT="8890"
          export KEYLIME_AGENT_ENABLE_AGENT_MTLS="true"
          export KEYLIME_AGENT_SERVER_KEY="server-private.pem"
          export KEYLIME_AGENT_SERVER_CERT="server-cert.crt"
          export KEYLIME_AGENT_TRUSTED_CLIENT_CA="cv_ca/cacert.crt"
    
    - name: Set ownership of /var/lib/keylime to keylime:tss
      file:
        path: /var/lib/keylime
        owner: keylime
        group: tss
        recurse: yes

    - name: Ensure Keylime CA directory exists
      ansible.builtin.file:
        path: /var/lib/keylime/cv_ca
        state: directory
        mode: '0755'

    - name: Copy entire RootCA to component
      ansible.builtin.copy:
        src: CA/cacert.crt
        dest: /var/lib/keylime/cv_ca/
        recurse: yes
        

- name: Configure Verifier
  hosts: keylime_verifier
  become: true
  pre_tasks:
    - name: Probe python installation
      raw: command -v python3 || true
      changed_when: false
      register: python_available
    - name: Bootstrap a host without python installed
      raw: dnf install python3 python3-libselinux
      when: "'python' not in python_available.stdout"
  roles:
    - ansible-keylime
  tasks:
    - name: Set Keylime verifier environment variables for root user
      blockinfile:
        path: /root/.bashrc
        marker: "# {mark} KEYLIME VERIFIER ENV VARS"
        block: |
          export KEYLIME_VERIFIER_IP="192.168.33.12"
          export KEYLIME_VERIFIER_PORT="8881"
          export KEYLIME_VERIFIER_REGISTRAR_IP="192.168.33.11"
          export KEYLIME_VERIFIER_REGISTRAR_PORT="8891"
          export KEYLIME_VERIFIER_TLS_DIR="/var/lib/keylime/cv_ca"
          export KEYLIME_VERIFIER_SERVER_KEY="server-private.pem"
          export KEYLIME_VERIFIER_SERVER_CERT="server-cert.crt"
          export KEYLIME_VERIFIER_TRUSTED_CLIENT_CA="['cacert.crt']"
          export KEYLIME_VERIFIER_CLIENT_KEY="client-private.pem"
          export KEYLIME_VERIFIER_CLIENT_CERT="client-cert.crt"
          export KEYLIME_VERIFIER_TRUSTED_SERVER_CA="['cacert.crt']"

    - name: Ensure Keylime CA directory exists
      ansible.builtin.file:
        path: /var/lib/keylime/cv_ca
        state: directory
        mode: '0755'
    - name: Copy entire RootCA to component
      ansible.builtin.copy:
        src: CA/cacert.crt
        dest: /var/lib/keylime/cv_ca/
        recurse: yes
    - name: Copy all files starting with 'server' from CA/ to component
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/keylime/cv_ca/
      with_fileglob:
        - "CA/server*"
    - name: Copy all files starting with 'client' from CA/ to component
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/keylime/cv_ca/
      with_fileglob:
        - "CA/client*"

      
  

- name: Configure Registrar
  hosts: keylime_registrar
  become: true
  pre_tasks:
    - name: Probe python installation
      raw: command -v python3 || true
      changed_when: false
      register: python_available
    - name: Bootstrap a host without python installed
      raw: dnf install python3 python3-libselinux
      when: "'python' not in python_available.stdout"
  roles:
    - ansible-keylime
  tasks:
    - name: Set Keylime registrar environment variables for root user
      blockinfile:
        path: /root/.bashrc
        marker: "# {mark} KEYLIME REGISTRAR ENV VARS"
        block: |
          export KEYLIME_REGISTRAR_IP="192.168.33.11"
          export KEYLIME_REGISTRAR_PORT="8890"
          export KEYLIME_REGISTRAR_TLS_PORT="8891"
          export KEYLIME_REGISTRAR_TLS_DIR="/var/lib/keylime/cv_ca"
          export KEYLIME_REGISTRAR_SERVER_KEY="server-private.pem"
          export KEYLIME_REGISTRAR_SERVER_CERT="server-cert.crt"
          export KEYLIME_REGISTRAR_TRUSTED_CLIENT_CA="cacert.pem"
    - name: Ensure Keylime CA directory exists
      ansible.builtin.file:
        path: /var/lib/keylime/cv_ca
        state: directory
        mode: '0755'
    - name: Copy entire RootCA to component
      ansible.builtin.copy:
        src: CA/cacert.crt
        dest: /var/lib/keylime/cv_ca/
        recurse: yes
    - name: Copy all files starting with 'server' from CA/ to component
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/keylime/cv_ca/
      with_fileglob:
        - "CA/server*"


- name: Configure Tenant
  hosts: keylime_tenant
  become: true
  pre_tasks:
    - name: Probe python installation
      raw: command -v python3 || true
      changed_when: false
      register: python_available
    - name: Bootstrap a host without python installed
      raw: dnf install python3 python3-libselinux
      when: "'python' not in python_available.stdout"
  roles:
    - ansible-keylime
  tasks:
    - name: Set Keylime tenant environment variables for root user
      blockinfile:
        path: /root/.bashrc
        marker: "# {mark} KEYLIME TENANT ENV VARS"
        block: |
          export KEYLIME_TENANT_VERIFIER_IP="192.168.33.12"
          export KEYLIME_TENANT_VERIFIER_PORT="8881"
          export KEYLIME_TENANT_REGISTRAR_IP="192.168.33.11"
          export KEYLIME_TENANT_REGISTRAR_PORT="8891"
          export KEYLIME_TENANT_TPM_CERT_STORE="/var/lib/keylime/tpm_cert_store"
          export KEYLIME_TENANT_TRUSTED_SERVER_CA="['cacert.crt']"
          export KEYLIME_TENANT_CLIENT_KEY="client-private.pem"
          export KEYLIME_TENANT_CLIENT_CERT="client-cert.crt"
    - name: Ensure Keylime CA directory exists
      ansible.builtin.file:
        path: /var/lib/keylime/cv_ca
        state: directory
        mode: '0755'

    - name: Copy entire RootCA to component
      ansible.builtin.copy:
        src: CA/cacert.crt
        dest: /var/lib/keylime/cv_ca/
        recurse: yes
    - name: Copy all files starting with 'client' from CA/ to component
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/lib/keylime/cv_ca/
      with_fileglob:
        - "CA/client*"
    

