---
- name: Configure Keylime Agent
  hosts: keylime_agent
  become: true
  pre_tasks:
    - name: Ensure Python 3 is available
      dnf:
        name: python3
        state: present
    - name: Install libselinux-python3
      dnf:
        name: libselinux-python3
        state: present    
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive
  roles:
    - ansible-keylime
    - tpm_setup

- name: Configure Keylime Registrars, Verifiers, and Tenants
  hosts: keylime_registrar,keylime_verifier,keylime_tenant
  become: true
  pre_tasks:
    - name: Probe python installation
      raw: command -v python3 || true
      changed_when: false
      register: python_available
    - name: Bootstrap a host without python installed
      raw: dnf install python3 python3-libselinux
      when: "'python' not in python_available.stdout"
  roles:
    - ansible-keylime
