- name: Ubuntu SWTPM install
  include_tasks: ubuntu_install.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Fedora SWTPM install
  include_tasks: fedora_install.yml
  when: ansible_facts['distribution'] == 'Fedora'
