---
# requirements
dependencies_fedora:
  ['autoconf',
   'autoconf-archive',
   'automake',
   'clang-devel',
   'dbus-devel',
   'gcc',
   'git',
   'glib2-devel',
   'keylime',
   'libcurl-devel',
   'libgcrypt-devel',
   'libstdc++-devel',
   'libtool',
   'libffi-devel',
   'pkg-config',
   'python3-cryptography',
   'python3-devel',
   'python3-pyyaml',
   'python3-yaml',
   'python3-simplejson',
   'python3-sqlalchemy',
   'python3-alembic',
   'redhat-rpm-config',
   'tpm2-tools',
   'tpm2-tss',
   'tpm2-tss-devel',
   'uriparser-devel',
   'efivar-devel',
   'cargo',
   'openssl-devel',
   'zeromq-devel',
   'libarchive-devel']
dependencies_ubuntu:
  - autoconf
  - autoconf-archive
  - automake
  - clang
  - dbus
  - gcc
  - git
  - libglib2.0-dev
  - libcurl4-openssl-dev
  - libgcrypt20-dev
  - libstdc++-12-dev
  - libtool
  - libffi-dev
  - pkg-config
  - python3-cryptography
  - python3-dev
  - python3-yaml
  - python3-simplejson
  - python3-sqlalchemy
  - python3-alembic
  - tpm2-tools
  - libtss2-dev
  - liburiparser-dev
  - libefivar-dev
  - cargo
  - libssl-dev
  - libzmq3-dev
  - libarchive-dev
  - libjson-c-dev
  - make
  - libclang-dev




# section for vars
shell_profiles:
  - .bash_profile

