keylime_registrar_ip: "0.0.0.0"
keylime_registrar_port: "8890"
keylime_registrar_tls_port: "8891"
keylime_registrar_tls_dir: "/var/lib/keylime/cv_ca"
keylime_registrar_server_key: "server-private.pem"
keylime_registrar_server_cert: "server-cert.crt"
keylime_registrar_trusted_client_ca: "['cacert.crt']"
