- name: Ubuntu keylime install
  include_tasks: ubuntu_install.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Fedora keylime install
  include_tasks: fedora_install.yml
  when: ansible_facts['distribution'] == 'Fedora'
