- name: Install dependencies on Ubuntu
  apt:
    name: "{{ dependencies_ubuntu }}"
    state: present
    update_cache: yes

- name: Clone tpm2-tss repository
  git:
    repo: 'https://github.com/tpm2-software/tpm2-tss.git'
    dest: '/opt/tpm2-tss'
    version: 'master'

- name: Build and install tpm2-tss
  shell: |
    cd /opt/tpm2-tss
    ./bootstrap
    ./configure --prefix=/usr
    make
    make install
  args:
    creates: /usr/lib/x86_64-linux-gnu/libtss2.so


- name: Install Rust 
  shell: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
  changed_when: false


- name: Clone Rust-Keylime
  git:
    repo: https://github.com/keylime/rust-keylime
    dest: /root/rust-keylime


- name: Build Rust-Keylime Agent
  shell: |
    source "$HOME/.cargo/env"
    cd /root/rust-keylime
    make && make install
    cargo build
  args:
    executable: /bin/bash

- name: Clone Python-keylime
  git:
    repo: https://github.com/keylime/keylime
    dest: /root/keylime

- name: Run the installer.sh script
  command: ./installer.sh
  args:
    chdir: /root/keylime


- name: Set TPM2TOOLS_TCTI environment variable
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^TPM2TOOLS_TCTI'
    line: 'TPM2TOOLS_TCTI="device:/dev/tpmrm0"'

- name: Make keylime and tss user , to enable userswitch in agent.
  script: ubuntu_support.sh
