- name: Ensure Keylime CA directory exists
  ansible.builtin.file:
    path: "{{ keylime_cert_dest }}"
    state: directory
    mode: '0755'

- name: Copy CA cert
  ansible.builtin.copy:
    src: "{{ keylime_rootca_cert }}"
    dest: "{{ keylime_cert_dest }}"
    owner: keylime
    group: tss
    mode: '0644'

- name: Copy additional certificates matching patterns
  include_tasks: copy_certs.yml
  loop: "{{ keylime_cert_patterns }}"
  loop_control:
    loop_var: cert_pattern
  when:
    - keylime_cert_patterns is defined
    - keylime_cert_patterns | length > 0


